# -*- coding: utf-8 -*-
"""30daysPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SWzXv9n5D_neFUYeq0P1sjazHW3VC_im

#This is the day three =D, exactly
"""

#1
age = int(input("Dame tu edad :"))
print(f'{age}')

#2
height = float(input("How height do  you have "))
print(f"your height is {height}")

#4: the area of this square
base = 20
height = 10
area = (base*height)/2
print(f"El Area es {area} ")

#5 Calculate the perimeter of the triangle
a =5
b = 4
c =3
print(f"the perimeter is :{ a+b+c}")

#6 Area of a rectangle,
length = 12
width = 3
print(f"The area is: {length*width} and the perimeter is: { 2*length + 2*width}")

#7  consigue el radio, no me dan ningun modo para calcular esto

#8 Calculate the slope, x-intercept and y-intercept of y = 2x -2

# y =0 , when y =0m x = 1, and when x= 0, y = -1
x =1
m1= 2
print(f"the slope is {m1}")
print(f"when y =0 the cuts with the axis y is in {x}")
# let's go to evaluate when y =0, clear x, then
y =-1
x = (y+2)/2
print(f"the cuts with the axis x is in:{x}")

#9 Slope is (m = y2-y1/x2-x1). Find the slope and Euclidean distance between point (2, 2) and point (6,10)
import math
y_1= 2
x_1=2
y_2=6
x_2=10

m2 =(y_2-y_1)/(x_2-x_1)
d =math.sqrt((y_2-y_1)**2+(x_2-x_1)**2 )

print(f"the slope is {m2} and the distnte between each point is : {d:.2f}")

#10 Compare the slopes in tasks 8 and 9.
#let's ho to see which slope is bigger
if m1 >= m2:
    print(f'm1 is the slope bigger {m1}')
else:
    print(f' m2 is the slope bigger {m2}')

#11 Calculate the value of y (y = x^2 + 6x + 9). Try to use different x values and figure out at what x value y is going to be 0.

